thrive1_user='thuntAPI1'
thrive1_pass='Squiggly3-Landlady-Quirk-Plunging-Hardhat'

thrive2_user='thuntAPI2'
thrive2_pass='Outscore7-Cycling-Unmapped-Scheme-Cheer'

thrive3_user='thuntAPI3'
thrive3_pass='Crown9-Denim-Creme-Giddiness-Parched'

thrive4_user='thuntAPI4'
thrive4_pass='Carried5-Plural-Handwoven-Tackle-Irate'

thrive5_user='thuntAPI5'
thrive5_pass='Tubular6-Untie-Remark-Handiness-Kelp'

thrive6_user='thuntAPI6'
thrive6_pass='Paprika4-Deviation-Wand-Sloped-Quarters'

sentinelone_us_key = 'Bearer eyJraWQiOiJ1cy1lYXN0LTEtcHJvZC0wIiwiYWxnIjoiRVMyNTYifQ.eyJzdWIiOiJzZXJ2aWNldXNlci02YWE0YWQ2Yy0wYWU4LTRjZDQtOWU0ZS0yNTA5ZWZjOWI5MDRAbWdtdC01NTc1NC5zZW50aW5lbG9uZS5uZXQiLCJpc3MiOiJhdXRobi11cy1lYXN0LTEtcHJvZCIsImRlcGxveW1lbnRfaWQiOiI1NTc1NCIsInR5cGUiOiJ1c2VyIiwiZXhwIjoxODQyNjE3MjM2LCJpYXQiOjE3Nzk0NjAwNDEsImp0aSI6ImRlYjVhZTA2LTdiNTEtNGRlMC1iZjljLTJjNDNhNGRiMGI0ZiJ9.3pTzdjEnfcvXlHz7j9WVcV8Qffmol9YR4Fs9VRCHpZu0eQ5UiV-6Els4ST7aiB1IJ6vKGg3Dr0TtYASLDxcI7g'
sentinelone_eu_key = 'Bearer eyJraWQiOiJldS1jZW50cmFsLTEtcHJvZC0wIiwiYWxnIjoiRVMyNTYifQ.eyJzdWIiOiJzZXJ2aWNldXNlci0xZjQzYzVjNy05MjkzLTRiMzktOTBhOS0xNGJkNTIyNzFhNDdAbWdtdC0xNDU4MC5zZW50aW5lbG9uZS5uZXQiLCJpc3MiOiJhdXRobi1ldS1jZW50cmFsLTEtcHJvZCIsImRlcGxveW1lbnRfaWQiOiIxNDU4MCIsInR5cGUiOiJ1c2VyIiwiZXhwIjoxODQyNjIxNjA3LCJpYXQiOjE3Nzk0NjQwMzgsImp0aSI6ImE0YWEzOGQ1LTNhYTMtNGI1My1iZDNjLWU4Y2Q0OWFlOWZkZSJ9.S7qEet0-Io98mh9zU5HAK1LZdd6l2Idpbpmf5OLhkI1LbM8lVkmEUWrgeXxbUnpQSCGiGn0unV_-y1JzCc63-w'
sentinelone_ca_key = 'Bearer eyJraWQiOiJjYS1jZW50cmFsLTEtcHJvZC0wIiwiYWxnIjoiRVMyNTYifQ.eyJzdWIiOiJzZXJ2aWNldXNlci00ZjM4MjEzZC0xYmEwLTRmMjEtYmI5MS1mN2Q4MThlODVmMGVAbWdtdC0xMDcuc2VudGluZWxvbmUubmV0IiwiaXNzIjoiYXV0aG4tY2EtY2VudHJhbC0xLXByb2QiLCJkZXBsb3ltZW50X2lkIjoiMTA3IiwidHlwZSI6InVzZXIiLCJleHAiOjE4NDI2MzA3MjAsImlhdCI6MTc3OTQ3MjM0MCwianRpIjoiZGJiNDkwZmQtYTJjNi00OTExLWFmNzUtNDZhNjk4MmRmOTMwIn0.3AhMX5MiU32CBuuPqkhButZMkFuzXVeBfgqcmnpUasr2OFKatqNYiOVCR9ALFOuEYylp48P1bD8M_YRWZgPbuw'

headers_us_s1 = {
  'Authorization': sentinelone_us_key,
  'Content-Type': 'application/json'
}

headers_eu_s1 = {
  'Authorization': sentinelone_eu_key,
  'Content-Type': 'application/json'
}

headers_ca_s1 = {
  'Authorization': sentinelone_ca_key,
  'Content-Type': 'application/json'
}